language: smalltalk
sudo: true

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then sudo easy_install pip ; fi
  - pip install --user benchupload

os:
  - linux
  - osx

smalltalk:
  - Pharo-6.1
  - Pharo-6.0
  - Pharo-7.0
  - Pharo64-6.1
  - Pharo64-7.0 

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD
